### ISSUE TITLE
pip install ./lxt 

### ISSUE THREAD

**Issue by GeorgeRodinos** [rachtibat/LRP-eXplains-Transformers#6]
$ git clone https://github.com/rachtibat/LRP-for-Transformers
$ pip install ./lxt

This doesn't work.

**Comment by rachtibat** [comment]
what is the error?

**Comment by rachtibat** [comment]
maybe `cd LRP-for-Transformers` first?

**Comment by GeorgeRodinos** [comment]
![Screenshot from 2024-07-01 15-43-49](https://github.com/rachtibat/LRP-eXplains-Transformers/assets/103505526/727af033-173d-4109-a182-288548b27b44)

**Comment by rachtibat** [comment]
```
git clone https://github.com/rachtibat/LRP-for-Transformers
cd LRP-for-Transformers/
pip install -e .
```

But I think, in your case simply install the stable release with `pip install lxt`.

Best
